### PR TITLE
Add prettier, update eslint rules

### PR DESCRIPTION
**Pull request by omladek**
Add prettier for automatic and consistent code formatting.
Set indent size to 2 spaces as discussed on FE team meeting.
Update all files to use trailling coma.
Enable autofixing in DEV mode of all fixable errors.

Settings were used and tested on Komercni banka and Panesco projects.

### CODE REVIEW

**Comment by zmrhaljiri** [comment]
Cool :) what about to disable semicolons?

**Comment by omladek** [comment]
Ad semicolon: it was discussed during FE meeting, that we do want to use semicolon.

**Comment by zmrhaljiri** [comment]
Yes? So I do have really bad memory. Chmm.. Let's rediscuss it then on the next one.

**Review by zmrhaljiri — APPROVED** [review]

**Comment by omladek** [comment]
Meeting notes: https://actumdigital.atlassian.net/wiki/spaces/FRON/pages/177569814/2018-05-14+Meeting+notes :-)

**Review by fidelman — APPROVED** [review]

**Pull request merged**
